name=L298N
version=2.1.0
author=林東頡
maintainer=sw10921sw@gmail.com
sentence=A simple, memorable, and powerful C-style library to easily control L298N motor drivers.
paragraph=This library provides a clean and intuitive BigCamelCase API designed in pure C style. It allows users to easily manage L298N motor drivers, supporting both standard (non-speed controlled) and PWM-based speed controlled motor objects with straightforward setup and control functions.
category=Device Control
url=https://github.com/cji-3/L298N
architectures=*
includes=L298N.h